#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Wed Jul 11 13:08:50 2018
#

import wx
import wx.lib.inspection
import functions
from glob import glob
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from wx.lib.agw.thumbnailctrl import ThumbnailCtrl
import wx.lib.agw.thumbnailctrl as TC
import os  # usado no path do dirselect
workinDir = os.getcwd()
# end wxGlade


class main(wx.Frame):
    def __init__(self, *args, **kwds):
        #wx.lib.inspection.InspectionTool().Show()

        # begin wxGlade: main.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 640))
        self.notebook = wx.Notebook(self, wx.ID_ANY)
        self.notebook_dir = wx.Panel(self.notebook, wx.ID_ANY)
        self.dirselect = wx.DirPickerCtrl(self.notebook_dir, wx.ID_ANY, path=workinDir)
        self.dirselect.Bind(wx.EVT_DIRPICKER_CHANGED, self.onChangeDir)
        self.thumbs = ThumbnailCtrl(self.notebook_dir, imagehandler=TC.NativeImageHandler)
        self.thumbs.ShowDir(workinDir)
        self.notebook_ConfiguracoesdoOPENCV = wx.Panel(self.notebook, wx.ID_ANY, style=wx.FULL_REPAINT_ON_RESIZE | wx.TAB_TRAVERSAL)
        self.panel_configs = wx.Panel(self.notebook_ConfiguracoesdoOPENCV, wx.ID_ANY)
        self.slider_h = wx.Slider(self.panel_configs, wx.ID_ANY, 0, 0, 179, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_s = wx.Slider(self.panel_configs, wx.ID_ANY, 0, 0, 255, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_v = wx.Slider(self.panel_configs, wx.ID_ANY, 0, 0, 255, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_h1 = wx.Slider(self.panel_configs, wx.ID_ANY, 179, 0, 179, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_s1 = wx.Slider(self.panel_configs, wx.ID_ANY, 68, 0, 255, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_v1 = wx.Slider(self.panel_configs, wx.ID_ANY, 166, 0, 255, style=wx.SL_HORIZONTAL | wx.SL_VALUE_LABEL)
        self.slider_imagens = wx.Slider(self.panel_configs, wx.ID_ANY, 0, 0, 10, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.panel_original = wx.Panel(self.notebook_ConfiguracoesdoOPENCV, wx.ID_ANY, style=wx.FULL_REPAINT_ON_RESIZE)
        self.panel_threshold = wx.Panel(self.notebook_ConfiguracoesdoOPENCV, wx.ID_ANY, style=wx.FULL_REPAINT_ON_RESIZE)
        self.notebook_saida = wx.Panel(self.notebook, wx.ID_ANY)
        self.text_separador = wx.TextCtrl(self.notebook_saida, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.list_classes = wx.ListCtrl(self.notebook_saida, wx.ID_ANY, style=wx.FULL_REPAINT_ON_RESIZE | wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.gauge = wx.Gauge(self.notebook_saida, wx.ID_ANY, 10)
        self.button_gerar = wx.Button(self.notebook_saida, wx.ID_ADD, "", style=wx.BORDER_NONE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_h)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_s)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_v)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_h1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_s1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_v1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_image_change, self.slider_imagens)
        self.Bind(wx.EVT_TEXT, self.onPressEnter, self.text_separador)
        self.Bind(wx.EVT_TEXT_ENTER, self.onPressEnter, self.text_separador)
        self.Bind(wx.EVT_BUTTON, self.onOk, self.button_gerar)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGING, self.changing, self.notebook)
        # end wxGlade

    def onChangeDir(self, event):
        global workinDir
        workinDir = self.dirselect.GetPath()
        self.thumbs.ShowDir(workinDir)

    def __set_properties(self):
        # begin wxGlade: main.__set_properties
        self.SetTitle("Classificacao de Cafes")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./icos/ico.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.text_separador.SetToolTip(u"Caracteres que separam a classe do nome da foto.\n\nN\u00e3o se pode ter o caractere . como separador")
        self.list_classes.AppendColumn("Classe", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_classes.AppendColumn("Quantidade", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.button_gerar.SetBackgroundColour(wx.Colour(9, 255, 20))
        self.button_gerar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.button_gerar.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: main.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_saida = wx.BoxSizer(wx.VERTICAL)
        sizer_gauge = wx.BoxSizer(wx.HORIZONTAL)
        sizer_separador = wx.BoxSizer(wx.HORIZONTAL)
        sizer_config = wx.BoxSizer(wx.VERTICAL)
        sizer_fotos = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_threshold = wx.StaticBoxSizer(wx.StaticBox(self.notebook_ConfiguracoesdoOPENCV, wx.ID_ANY, "Threshold"), wx.VERTICAL)
        self.sizer_original = wx.StaticBoxSizer(wx.StaticBox(self.notebook_ConfiguracoesdoOPENCV, wx.ID_ANY, "Original"), wx.VERTICAL)
        sizer_configs = wx.BoxSizer(wx.VERTICAL)
        sizer_slider_fotos = wx.StaticBoxSizer(wx.StaticBox(self.panel_configs, wx.ID_ANY, "Fotos"), wx.VERTICAL)
        sizer_limite_inferior = wx.StaticBoxSizer(wx.StaticBox(self.panel_configs, wx.ID_ANY, "Limite superior (h,s,v)"), wx.VERTICAL)
        sizer_h1s1v1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_limite_superior = wx.StaticBoxSizer(wx.StaticBox(self.panel_configs, wx.ID_ANY, "Limite inferior (h,s,v)"), wx.VERTICAL)
        sizer_hsv = wx.BoxSizer(wx.HORIZONTAL)
        sizer_dir = wx.BoxSizer(wx.VERTICAL)
        sizer_dir.Add(self.dirselect, 0, wx.ALL | wx.EXPAND, 0)
        sizer_dir.Add(self.thumbs, 1, wx.ALL | wx.EXPAND, 0)
        self.notebook_dir.SetSizer(sizer_dir)
        sizer_hsv.Add(self.slider_h, 1, 0, 0)
        sizer_hsv.Add(self.slider_s, 1, 0, 0)
        sizer_hsv.Add(self.slider_v, 1, 0, 0)
        sizer_limite_superior.Add(sizer_hsv, 1, wx.EXPAND, 0)
        sizer_configs.Add(sizer_limite_superior, 1, wx.EXPAND, 0)
        sizer_h1s1v1.Add(self.slider_h1, 1, wx.EXPAND, 0)
        sizer_h1s1v1.Add(self.slider_s1, 1, wx.EXPAND, 0)
        sizer_h1s1v1.Add(self.slider_v1, 1, wx.EXPAND, 0)
        sizer_limite_inferior.Add(sizer_h1s1v1, 1, wx.EXPAND, 0)
        sizer_configs.Add(sizer_limite_inferior, 1, wx.EXPAND, 0)
        sizer_slider_fotos.Add(self.slider_imagens, 0, wx.EXPAND, 0)
        sizer_configs.Add(sizer_slider_fotos, 1, wx.EXPAND, 0)
        self.panel_configs.SetSizer(sizer_configs)
        sizer_config.Add(self.panel_configs, 1, wx.EXPAND, 0)
        self.sizer_original.Add(self.panel_original, 1, wx.ALL | wx.EXPAND, 2)
        sizer_fotos.Add(self.sizer_original, 1, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 0)
        self.sizer_threshold.Add(self.panel_threshold, 1, wx.ALL | wx.EXPAND, 2)
        sizer_fotos.Add(self.sizer_threshold, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_config.Add(sizer_fotos, 2, wx.EXPAND, 0)
        self.notebook_ConfiguracoesdoOPENCV.SetSizer(sizer_config)
        label_separardor = wx.StaticText(self.notebook_saida, wx.ID_ANY, "Separador  ", style=wx.ALIGN_CENTER | wx.ST_ELLIPSIZE_MIDDLE)
        sizer_separador.Add(label_separardor, 0, wx.ALIGN_CENTER | wx.ALL | wx.SHAPED, 0)
        sizer_separador.Add(self.text_separador, 0, wx.ALIGN_CENTER, 0)
        sizer_saida.Add(sizer_separador, 0, wx.ALL, 1)
        sizer_saida.Add(self.list_classes, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_gauge.Add(self.gauge, 1, wx.EXPAND, 0)
        sizer_gauge.Add(self.button_gerar, 0, wx.ALIGN_CENTER, 0)
        sizer_saida.Add(sizer_gauge, 0, wx.EXPAND, 0)
        self.notebook_saida.SetSizer(sizer_saida)
        self.notebook.AddPage(self.notebook_dir, "Diretorio de trabalho")
        self.notebook.AddPage(self.notebook_ConfiguracoesdoOPENCV, "Configuracoes do OPENCV")
        self.notebook.AddPage(self.notebook_saida, "Configuracoes da saida")
        sizer_main.Add(self.notebook, 1, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        self.Layout()
        # end wxGlade
        bitmap_1 = wx.StaticBitmap(self.panel_original,
                                   wx.ID_ANY, 
                                   wx.Bitmap(
                                        ".\\icos\\img.ico",
                                    wx.BITMAP_TYPE_ANY))
        bitmap_2 = wx.StaticBitmap(self.panel_threshold,
                                   wx.ID_ANY, wx.Bitmap(
                                       ".\\icos\\img.ico",
                                       wx.BITMAP_TYPE_ANY))

    def slider_image_change(self, event):  # wxGlade: main.<event_handler>

        id = self.slider_imagens.GetValue()
        path = globs[id]

        for child in self.panel_original.GetChildren():
            child.Destroy()
        wx.StaticBitmap(self.panel_original, wx.ID_ANY, functions.genImage(
            path, *self.sizer_original.GetSize()))

        for child in self.panel_threshold.GetChildren():
            child.Destroy()
        conf = [
            self.slider_h.GetValue(), self.slider_s.GetValue(),
            self.slider_v.GetValue(), self.slider_h1.GetValue(),
            self.slider_s1.GetValue(), self.slider_v1.GetValue()
        ]

        wx.StaticBitmap(self.panel_threshold, wx.ID_ANY, functions.threshold(
            path, size=self.sizer_threshold.GetSize(), hsv=conf))

    def changing(self, event):  # wxGlade: main.<event_handler>
        global globs
        globs = glob(workinDir + "/*.jpg")

        if(len(globs) > 1):
            self.slider_imagens.SetValue(0)
            self.slider_imagens.SetMax(len(globs) - 1)
            self.slider_imagens.Enable(True)
            self.slider_image_change([])
        else:
            self.slider_imagens.Enable(False)
            self.slider_imagens.SetValue(0)
            self.slider_imagens.SetMax(1)
            for child in self.panel_original.GetChildren():
                child.Destroy()
            for child in self.panel_threshold.GetChildren():
                child.Destroy()
            wx.StaticBitmap(self.panel_original, wx.ID_ANY, wx.Bitmap(
                "C:\\Users\\Rout\\Documents\\wxpython\\img.ico", wx.BITMAP_TYPE_ANY))
            wx.StaticBitmap(self.panel_threshold, wx.ID_ANY, wx.Bitmap(
                "C:\\Users\\Rout\\Documents\\wxpython\\img.ico", wx.BITMAP_TYPE_ANY))

    def onPressEnter(self, event):  # wxGlade: main.<event_handler>
        self.list_classes.DeleteAllItems()
        classes = functions.makeClass(globs, self.text_separador.GetValue())
        for classe, quantidade in classes.items():
            self.list_classes.Append([classe, quantidade])
    def onOk(self, event):  # wxGlade: main.<event_handler>
        self.gauge.SetValue(10)
# end of class main


class MyApp(wx.App):
    def OnInit(self):
        self.frame = main(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
